<?php

namespace BookBundle\Repository\Forms;

/**
 * PersonageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonageRepository extends \Doctrine\ORM\EntityRepository
{
}
